#!/usr/bin/env bash

# set env registry
eval $(docker-machine env registry)

# build app image
docker build -t php_fpm_app ./phpfpm/

# tag app image
docker tag php_fpm_app $(docker-machine ip registry):5000/php_fpm_app

# push app image to registry
docker push $(docker-machine ip registry):5000/php_fpm_app

# build app image
docker build -t haproxy_server ./haproxy/

# tag app image
docker tag haproxy_server $(docker-machine ip registry):5000/haproxy_server

# push app image to registry
docker push $(docker-machine ip registry):5000/haproxy_server
