#!/usr/bin/env bash

export CONSUL_IP=$(docker-machine ip consul)

# set env
eval $(docker-machine env -swarm swarm-master)

# create overlay network
docker network create --driver overlay --subnet=10.0.9.0/24 app

# up containers
docker-compose -f docker-compose.yml up -d
