#!/usr/bin/env bash

export CONSUL_IP=$(docker-machine ip consul)

#export REGISTRY_IP=$(docker-machine ip registry)
#docker build -t php_fpm_app ./phpfpm/
#docker tag php_fpm_app $(docker-machine ip registry):5000/php_fpm_app
#docker push $(docker-machine ip registry):5000/php_fpm_app

# set env
eval $(docker-machine env -swarm swarm-master)

# create overlay network
docker network create --driver overlay --subnet=10.0.9.0/24 app

# up containers
docker-compose -f docker-compose.yml up -d
