#!/usr/bin/env bash

export CONSUL_IP=$(docker-machine ip consul)

export REGISTRY_IP=$(docker-machine ip registry)

# push app image to registry
docker push $(docker-machine ip registry):5000/haproxy_server

# set env swarm-master
eval $(docker-machine env -swarm swarm-master)

# create overlay network
docker network create --driver overlay --subnet=10.0.9.0/24 app

# up containers
docker-compose up -d
