#!/usr/bin/env bash

# vm swarm master
docker-machine create \
    -d virtualbox \
    --swarm \
    --swarm-master \
    --swarm-discovery="consul://$(docker-machine ip consul):8500"\
    --engine-opt="cluster-store=consul://$(docker-machine ip consul):8500" \
    --engine-opt="cluster-advertise=eth1:2376" \
    swarm-master

# vm nginx
docker-machine create \
	-d virtualbox \
    --swarm \
    --swarm-discovery="consul://$(docker-machine ip consul):8500"\
    --engine-opt="cluster-store=consul://$(docker-machine ip consul):8500" \
    --engine-opt="cluster-advertise=eth1:2376" \
    --engine-label host=nginx \
    nginx

# vm mysql
docker-machine create \
	-d virtualbox \
    --swarm \
    --swarm-discovery="consul://$(docker-machine ip consul):8500"\
    --engine-opt="cluster-store=consul://$(docker-machine ip consul):8500" \
    --engine-opt="cluster-advertise=eth1:2376" \
    --engine-label host=mysql \
    mysql

# vm app server 1 and 2
for i in `seq 1 2`
do
  docker-machine create \
    -d virtualbox \
      --swarm \
      --swarm-discovery="consul://$(docker-machine ip consul):8500"\
      --engine-opt="cluster-store=consul://$(docker-machine ip consul):8500" \
      --engine-opt="cluster-advertise=eth1:2376" \
      --engine-label host=app-server \
      app-server-$i
done
